# Generated by Django 5.1 on 2024-08-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=15, unique=True, verbose_name='Cédula')),
                ('primer_nombre', models.CharField(max_length=30, verbose_name='Primer nombre')),
                ('primer_apellido', models.CharField(max_length=30, verbose_name='Primer apellido')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(verbose_name='Existencia')),
                ('gravable', models.BooleanField(default=True, verbose_name='Se grava ISV')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Tienda')),
                ('direccion', models.TextField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion de la orden')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado'), (3, 'Entregado'), (4, 'Cancelado'), (5, 'Reversado')], default=1, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='factura.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.tienda'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Vendedor')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.tienda')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.vendedor'),
        ),
    ]
